services:
  - type: web
    name: project-one
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOCAL_PORT
        fromService:
          type: web
          name: project-one
          property: port

